static_resources:
  listeners:
  - name: listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 5678 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.wasm
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
          terminal: true
          config:
            name: "echo"
            vm_config:
              code:
                local:
                  filename: "../proxy-wasm-filter/filter.wasm"

