[package]
name = "hyperlight"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
hyperlight_wasm = { version = "0.9.0-preview", registry = "hyperlight_packages", default-features = false, features = ["kvm"] }
